<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/register','LoginController@GetRegister')->name('Registration');
Route::post('/registerStore','LoginController@registrationStore')->name('StoreRegister');
Route::get('/login','LoginController@loginpage')->name('login')->middleware('guest');
Route::post('/logout','LoginController@logoutAccount')->name('Logging.out');
Route::post('/login-submit','LoginController@loginSubmit')->name('login-submit');
Route::resource('/','ItemsController');
Route::get('/SearchByItemCode','ItemsController@searchByItemCode')->name('search.code');
Route::get('/MIRS-add','MIRSController@MIRScreate')->name('mirs.add');
Route::get('/findMasterItem','ItemsController@searchItemMaster')->name('searchItemMaster');
Route::post('/sessionMIRSitem','MIRSController@addingSessionItem')->name('selecting.item');
Route::DELETE('/removeSessions/{id}','MIRSController@deletePartSession')->name('delete.session');
Route::post('mirs-storedata','MIRSController@StoringMIRS')->name('mirs.store');
Route::post('download-pdf','PDFController@pdf')->name('mirs-download');
Route::get('search-mirs','MIRSController@fullMIRSNo')->name('full-mirs');
Route::post('denied','MIRSController@DeniedMIRS')->name('DeniedMIRS');
Route::post('MCTstore','MCTController@StoreMCT')->name('Storing.MCT');
Route::get('MCTpreview','MCTController@previewMCT')->name('previewMCT');
Route::post('mct-download','PDFController@mctpdf')->name('print-mct');
Route::get('MRT-create','MRTController@CreateMRT')->name('create.mrt');
Route::post('MRT-store','MRTController@StoreMRT')->name('storing.mrt');
Route::post('MRT-session','MRTController@addToSession')->name('Session.addings');
Route::delete('MRT-delete/{id}','MRTController@deletePartSession')->name('mrtSession.deleting');
Route::get('MIRS-index','MIRSController@Indexgrid')->name('MIRSgridview');
Route::get('findmirs','MIRSController@searchMIRSNo')->name('finding.mirs');
Route::get('summary-mrt','MRTController@summaryMRT')->name('summary.mrt');
Route::get('mrt-find-date','MRTController@MRTSearchdate')->name('mrt.summary.find');
Route::get('mrt-print-summary','PDFController@mrtpdf')->name('mrt-summary-print');
Route::get('mrt-viewer','MRTController@mrtviewing')->name('mrt-viewer');
Route::get('mct-summary','MCTController@summaryMCT')->name('mct-summary');
Route::post('MIRS-Signature','MIRSController@MIRSSignature')->name('MIRSSign');
Route::get('Items-ByDescription','ItemsController@ItemMasterbyDescription')->name('ItemsearchDescription');
Route::post('Signature-for-mct','MCTController@SignatureMCT')->name('MCTsignature');
Route::get('mirs-signature-list','MIRSController@mirsRequestcheck')->name('checkmyMIRSrequest');
Route::get('mct-signature-request','MCTController@mctRequestcheck')->name('checkmyMCTrequest');
Route::get('ready-mirs','MIRSController@readyForMCT')->name('mirs-ready');
Route::get('MakeRR','RRController@CreateRR')->name('MakeRR');
Route::post('RRstoreSession','RRController@StoreSessionRRnonExisting')->name('RRSession');
Route::DELETE('DeleteSession-RR/{id}','RRController@deleteSessionStored')->name('RRDeleteSession');
Route::get('RRsearchitembyCode','RRController@searchbyItemMasterCode')->name('RRSearchItemCode');
Route::get('RRsearchitembydescription','RRController@ItemMasterbyDescription')->name('SearchbyDescriptionRR');
Route::post('RRaddingSessionFromExistingItem','RRController@StoreSessionItemExist')->name('addExistingToSession');
Route::post('RRsavingtoDB','RRController@StoringRRtoTable')->name('SaveRRtoDB');
Route::get('RR-index','RRController@RRindex')->name('RRindexview');
Route::get('RR-fullpreview/{id}','RRController@previewRR')->name('RRfullpreview');
Route::post('RR-signature','RRController@signatureRR')->name('RRsigning');
Route::get('RR-search-byRRNo','RRController@RRindexSearchbyRRNo')->name('RRSearchNo');
Route::get('checkout-rr-request','RRController@RRsignatureRequest')->name('checkmyRRrequest');
Route::POST('printRRpdf','PDFController@rrdownload')->name('RR-printing');
Route::post('decline-this-RR','RRController@declineRR')->name('RRdecline');
Route::get('RV-create','RVController@RVcreate')->name('Creating.RV');
Route::post('SessionSave','RVController@SaveSession')->name('SavingSessionRV');
Route::DELETE('DeleteSession/{id}','RVController@DeleteSession')->name('DeletingSessionRV');
Route::post('SavetoDBRR','RVController@savingToTable')->name('SavingRRtoDB');
Route::get('RVindex','RVController@RVindexView')->name('RVindexView');
Route::get('RVfullview/{id}','RVController@RVfullPreview')->name('RVfullpreviewing');
Route::post('RVsignature','RVController@Signature')->name('SignatureThisRV');
Route::get('myRVrequest','RVController@RVrequest')->name('MyRVrequestlist');
Route::post('declineRV','RVController@declineRV')->name('DeclineRV');
Route::get('search-rv','RVController@searchRV')->name('SearchingRV');
